### ISSUE TITLE
LAS-Diffusion on colab

### ISSUE THREAD

**Issue by PongpreechaSuea** [Zhengxinyang/LAS-Diffusion#2]
I tried getting your github deployed on Colab by clone.

But after following your README.md File

I tried running the command : !bash scripts/train_sketch.sh
I want to know how to fix it

And found an error :

raceback (most recent call last):
  File "__init__.pxd", line 942, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/skimage/__init__.py", line 121, in <module>
    from ._shared import geometry
  File "skimage/_shared/geometry.pyx", line 8, in init skimage._shared.geometry
  File "__init__.pxd", line 944, in numpy.import_array
ImportError: numpy.core.multiarray failed to import

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/LAS-Diffusion/train.py", line 3, in <module>
    from network.model_trainer import DiffusionModel
  File "/content/LAS-Diffusion/network/model_trainer.py", line 5, in <module>
    from network.data_loader import occupancy_field_Dataset
  File "/content/LAS-Diffusion/network/data_loader.py", line 6, in <module>
    import skimage.measure
  File "/usr/local/lib/python3.10/dist-packages/skimage/__init__.py", line 124, in <module>
    _raise_build_error(e)
  File "/usr/local/lib/python3.10/dist-packages/skimage/__init__.py", line 102, in _raise_build_error
    raise ImportError("""%s
ImportError: numpy.core.multiarray failed to import
It seems that scikit-image has not been built correctly.

Your install of scikit-image appears to be broken.
Try re-installing the package following the instructions at:
https://scikit-image.org/docs/stable/install.html 
Traceback (most recent call last):
  File "__init__.pxd", line 942, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .

**Comment by Zhengxinyang** [comment]
It looks like there is a version conflict between skimage and numpy. I'm sorry I haven't run the code on colab, maybe someone else has a solution?
